// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform => web;

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAe6gW2dWMrgFkUM2RBMAVYKwk3nEW3pBQ',
    appId: '1:171763188147:web:b2a94d7e26ead2eb300bc6',
    messagingSenderId: '171763188147',
    projectId: 'sominword',
    authDomain: 'sominword.firebaseapp.com',
    storageBucket: 'sominword.firebasestorage.app',
  );
}
